run:
  timeout: 5m
linters:
  enable: 
    - contextcheck
    - errorlint
    - gci
    - gofmt
    - gofumpt
    - gosimple
    - structcheck
    - unparam
  disable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused 
linters-settings:
  gci:
    local-prefixes: github.com/aquasecurity/fanal
