run:
  timeout: 5m
linters:
  enable: 
    - contextcheck
    - errorlint
    - gofmt
    - gofumpt
  disable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - unused 
