from --platform=$BUILDPLATFORM ghcr.io/westonsteimel/containerd:1.6.1 as source
from alpine
COPY --from=source /usr/local/bin/ /usr/local/bin/
RUN apk add bash
RUN ls /usr/local/bin
ENTRYPOINT ["/usr/local/bin/containerd"]
CMD ["--help"]