name: Benchmark
on: pull_request
jobs:
  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libdb-dev

    - name: Install cob
      run: curl -sfL https://raw.githubusercontent.com/knqyf263/cob/master/install.sh | sudo sh -s -- -b /usr/local/bin

    - name: Run Benchmark
      run: cob --threshold 0.7 --base origin/main --bench-cmd make --bench-args test-performance
