name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1 
    - name: Install dependencies
      run: sudo apt-get install libdb-dev

    - name: Run unit tests
      run: make test

  integration:
    name: Integration Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: test
      run: |
        docker version
        env

    - name: Install dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: brew install rpm

    - name: Install dependencies on Linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install rpm

    - name: Run integration tests
      run: make test-integration
