name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1 

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libdb-dev

    - name: Run unit tests
      run: make test

  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libdb-dev

    - name: Run integration tests
      run: make test-integration
