name: Windows Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  unittest:
    name: Unit Test
    runs-on: windows-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1 

    - name: Run unit tests
      run: go test ./...
